### ISSUE TITLE
Can't select anything

### ISSUE THREAD

**Issue by Bigfellas** [jneilliii/Octoprint-STLViewer#15]
I was wondering if I am doing something wrong. I dont get the option to select anything in the STL viewer. Currently running 1.2.2. Worked a while back. Not sure what version of software.

Thanks 
Matt

**Comment by jneilliii** [comment]
What browser are you using?  I just did a fresh install of both OctoPrint master branch (Version: 1.2.2-1-g85ad85b) and the master branch of STL-Viewer and it seems to be working as expected in Google Chrome.  Do you see the pull down lists at all? Do you have a login configured on your octoprint?  My set-up utilizes the haproxy for managing authentication and I don't use the login built into the octoprint software.  That may cause some timing issues with file loading, but not really sure.  The file list should be updating upon making the tab active.

**Comment by Bigfellas** [comment]
I am currently using chrome. I have tried IE aswell. I have also tried on a mac and PC. I have 2 installs of octopi and it doesn't work on either.

**Comment by jneilliii** [comment]
I've built my OctoPrint from scratch following instructions by foosel in the wiki.  I'm not sure how well guysoft keeps up with foosel updates on his images. What about the other questions?

**Comment by jneilliii** [comment]
I was able to reproduce your issue with the default octopi install.  I think the issue is related to the tab being initially hidden.  During development I had the GCode Visualizer tab disabled and the STL Viewer tab is visible without being collapsed.  I think that is causing the file list to not load properly on tab change.

**Comment by jneilliii** [comment]
So I just imaged the 1.2.2 version of OctoPi on a fresh sd card and installed the STL Viewer plugin and it seems to be working fine for me. Are you sure you have stl files uploaded to your pi?  I initially was not getting a list and realized I didn't have any files there since it was a fresh install.

**Comment by Bigfellas** [comment]
yup defiantly have some STL files in there. MMMM interesting i wonder if another plugin is conflicting. I might try a clean install.

**Comment by Bigfellas** [comment]
I've just tried a clean install of 1.2 and only installed stl viewer no go. updated to 1.2.2 still no go.

**Comment by jneilliii** [comment]
Sorry, I'm unable to reproduce the issue you're having.  If you open developer tools in chrome, does it show any errors in the console on page load?

**Comment by Bigfellas** [comment]
Only this. No idea if it is related 

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
packed_app.js?dc38c099:18739 Starting dependency resolution...

**Comment by jneilliii** [comment]
No,  I get that error too, it's part of the core octoprint.

**Comment by WIprinter** [comment]
Just an FYI. I get the same/similar results as Bigfellas. I compiled Octo from source Release 1.2.3, and then updated to Version: 1.3.0.dev79+g1b594b2. I get a drop down that just says "Choose" but nothing is available. I am using Chrome Version 43.0.2357.132 m (Latest version as of 7-10-15) I went to https://code.google.com/p/jsc3d/ and tried out the examples since you reference the base, and they all work fine.
![stl-viewer](https://cloud.githubusercontent.com/assets/8836605/8631827/3bea5d9a-2747-11e5-9448-1a438d0a2c5b.jpg)

**Comment by jneilliii** [comment]
Code for ontabchange to update the file list was missing due to github mishap.  All my testing involved uploading stl files, which also updates the file list pull-down.  This has been corrected and should now work as expected.  Go into plugin manager in settings, delete the plugin, restart the octoprint service, and install fresh from the plugin manager and you should be good to go.  Make sure to reload, which I think it warns you about now, which I think is a great addition by @foosel.

**Comment by Bigfellas** [comment]
This hasn't worked for me by the way. I have tried several times and installed it manually.

**Comment by jromero** [comment]
I'm running into the exact same issue... Octoprint version 1.2.16.

**Comment by jneilliii** [comment]
Does anything change when you switch away from the stl tab and back in?  I don't actually use this plugin personally, but I just installed on my current build and I didn't have an stl file uploaded.  I added one but the file list wasn't updated.  I switched away from the tab and re-selected the tab and the file list updated.

**Comment by ebaystudio** [comment]
Having this same issue. Using the most recent version of Octoprint and Chrome. Just a dropdown and nothing inside. 

This is the PrusaPrint version if that helps.

**Comment by jneilliii** [comment]
@ebaystudio, have you uploaded stl files and the file list on the left sidebar is not filtered to only show gcode files?

**Comment by ebaystudio** [comment]
Yes Ive been printing stuff all week. Ive loaded, deleted a bunch of files and nothing. Ive rebooted the pi a few times and still nothing. 

Here is a screen grab I just took. Im currently running a print but its the same regardless of it printing something or not. 

![image1](https://user-images.githubusercontent.com/39779766/46315619-e9540300-c59b-11e8-8d9b-8b40f57bd39b.png)

**Comment by jneilliii** [comment]
Yeah, the only thing that you are showing in the screenshot is gcode files, not stl files. This plugin will only show stl files, not gcode files.

**Comment by ebaystudio** [comment]
No that's the STL viewer. It's in the drop-down menu on the top right. Gcode viewer is a white grid. 

Edit. Never mind Im an idiot. For some reason, I thought it displayed the model as an STL does.

**Comment by jneilliii** [comment]
I don't think you are understanding what I'm saying.  The plugin will not render files of type `gcode`, only files of type `stl`.  This means that if you don't upload **pre-sliced stl** files there is nothing on your OctoPrint server for it to display.

**Comment by ebaystudio** [comment]
I get it, I just edited my reply when you replied. Sorry for the confusion.
